sudo: false
language: ruby
rvm:
  - 2.2.4
  - 2.2.1
  - 2.3.0
  - 2.3.3
  - 2.4.1
  - jruby
before_install: gem install bundler flay rubocop
install:
  - bundle install --retry=3 --with development
script:
  - bundle exec rake test
  - bundle exec rubocop
  - bundle exec flay
